import { indiaStateList } from './IndiaStateList';

export const countryList = [
  {
    key: 'Select',
    value: '',
  },
  //   { key: 'Albania', value: 'AL' },
  //   { key: 'Åland Islands', value: 'AX' },
  //   { key: 'Algeria', value: 'DZ' },
  //   { key: 'American Samoa', value: 'AS' },
  //   { key: 'Andorra', value: 'AD' },
  //   { key: 'Angola', value: 'AO' },
  //   { key: 'Anguilla', value: 'AI' },
  //   { key: 'Antarctica', value: 'AQ' },
  //   { key: 'Antigua and Barbuda', value: 'AG' },
  //   { key: 'Argentina', value: 'AR' },
  //   { key: 'Armenia', value: 'AM' },
  //   { key: 'Aruba', value: 'AW' },
  //   { key: 'Australia', value: 'AU' },
  //   { key: 'Austria', value: 'AT' },
  //   { key: 'Azerbaijan', value: 'AZ' },
  //   { key: 'Bahamas (the)', value: 'BS' },
  //   { key: 'Bahrain', value: 'BH' },
  //   { key: 'Bangladesh', value: 'BD' },
  //   { key: 'Barbados', value: 'BB' },
  //   { key: 'Belarus', value: 'BY' },
  //   { key: 'Belgium', value: 'BE' },
  //   { key: 'Belize', value: 'BZ' },
  //   { key: 'Benin', value: 'BJ' },
  //   { key: 'Bermuda', value: 'BM' },
  //   { key: 'Bhutan', value: 'BT' },
  //   { key: 'Bolivia (Plurinational State of)', value: 'BO' },
  //   { key: 'Bonaire, Sint Eustatius and Saba', value: 'BQ' },
  //   { key: 'Bosnia and Herzegovina', value: 'BA' },
  //   { key: 'Botswana', value: 'BW' },
  //   { key: 'Bouvet Island', value: 'BV' },
  //   { key: 'Brazil', value: 'BR' },
  //   { key: 'British Indian Ocean Territory (the)', value: 'IO' },
  //   { key: 'Brunei Darussalam', value: 'BN' },
  //   { key: 'Bulgaria', value: 'BG' },
  //   { key: 'Burkina Faso', value: 'BF' },
  //   { key: 'Burundi', value: 'BI' },
  //   { key: 'Cabo Verde', value: 'CV' },
  //   { key: 'Cambodia', value: 'KH' },
  //   { key: 'Cameroon', value: 'CM' },
  //{ key: 'Canada', value: 'CA' },
  //   { key: 'Cayman Islands (the)', value: 'KY' },
  //   { key: 'Central African Republic (the)', value: 'CF' },
  //   { key: 'Chad', value: 'TD' },
  //   { key: 'Chile', value: 'CL' },
  //{ key: 'China', value: 'CN' },
  //   { key: 'Christmas Island', value: 'CX' },
  //   { key: 'Cocos (Keeling) Islands (the)', value: 'CC' },
  //   { key: 'Colombia', value: 'CO' },
  //   { key: 'Comoros (the)', value: 'KM' },
  //   { key: 'Congo (the Democratic Republic of the)', value: 'CD' },
  //   { key: 'Congo (the)', value: 'CG' },
  //   { key: 'Cook Islands (the)', value: 'CK' },
  //   { key: 'Costa Rica', value: 'CR' },
  //   { key: 'Croatia', value: 'HR' },
  //   { key: 'Cuba', value: 'CU' },
  //   { key: 'Curaçao', value: 'CW' },
  //   { key: 'Cyprus', value: 'CY' },
  //   { key: 'Czechia', value: 'CZ' },
  //   { key: "Côte d'Ivoire", value: 'CI' },
  //   { key: 'Denmark', value: 'DK' },
  //   { key: 'Djibouti', value: 'DJ' },
  //   { key: 'Dominica', value: 'DM' },
  //   { key: 'Dominican Republic (the)', value: 'DO' },
  //   { key: 'Ecuador', value: 'EC' },
  //   { key: 'Egypt', value: 'EG' },
  //   { key: 'El Salvador', value: 'SV' },
  //   { key: 'Equatorial Guinea', value: 'GQ' },
  //   { key: 'Eritrea', value: 'ER' },
  //   { key: 'Estonia', value: 'EE' },
  //   { key: 'Eswatini', value: 'SZ' },
  //   { key: 'Ethiopia', value: 'ET' },
  //   { key: 'Falkland Islands (the) [Malvinas]', value: 'FK' },
  //   { key: 'Faroe Islands (the)', value: 'FO' },
  //   { key: 'Fiji', value: 'FJ' },
  //   { key: 'Finland', value: 'FI' },
  //   { key: 'France', value: 'FR' },
  //   { key: 'French Guiana', value: 'GF' },
  //   { key: 'French Polynesia', value: 'PF' },
  //   { key: 'French Southern Territories (the)', value: 'TF' },
  //   { key: 'Gabon', value: 'GA' },
  //   { key: 'Gambia (the)', value: 'GM' },
  //   { key: 'Georgia', value: 'GE' },
  //   { key: 'Germany', value: 'DE' },
  //   { key: 'Ghana', value: 'GH' },
  //   { key: 'Gibraltar', value: 'GI' },
  //   { key: 'Greece', value: 'GR' },
  //   { key: 'Greenland', value: 'GL' },
  //   { key: 'Grenada', value: 'GD' },
  //   { key: 'Guadeloupe', value: 'GP' },
  //   { key: 'Guam', value: 'GU' },
  //   { key: 'Guatemala', value: 'GT' },
  //   { key: 'Guernsey', value: 'GG' },
  //   { key: 'Guinea', value: 'GN' },
  //   { key: 'Guinea-Bissau', value: 'GW' },
  //   { key: 'Guyana', value: 'GY' },
  //   { key: 'Haiti', value: 'HT' },
  //   { key: 'Heard Island and McDonald Islands', value: 'HM' },
  //   { key: 'Holy See (the)', value: 'VA' },
  //   { key: 'Honduras', value: 'HN' },
  //   { key: 'Hong Kong', value: 'HK' },
  //   { key: 'Hungary', value: 'HU' },
  //   { key: 'Iceland', value: 'IS' },
  { key: 'India', value: 'IN' },
  //   { key: 'Indonesia', value: 'ID' },
  //   { key: 'Iran (Islamic Republic of)', value: 'IR' },
  //   { key: 'Iraq', value: 'IQ' },
  //   { key: 'Ireland', value: 'IE' },
  //   { key: 'Isle of Man', value: 'IM' },
  //   { key: 'Israel', value: 'IL' },
  //   { key: 'Italy', value: 'IT' },
  //   { key: 'Jamaica', value: 'JM' },
  //   { key: 'Japan', value: 'JP' },
  //   { key: 'Jersey', value: 'JE' },
  //   { key: 'Jordan', value: 'JO' },
  //   { key: 'Kazakhstan', value: 'KZ' },
  //   { key: 'Kenya', value: 'KE' },
  //   { key: 'Kiribati', value: 'KI' },
  //   { key: "Korea (the Democratic People's Republic of)", value: 'KP' },
  //   { key: 'Korea (the Republic of)', value: 'KR' },
  //   { key: 'Kuwait', value: 'KW' },
  //   { key: 'Kyrgyzstan', value: 'KG' },
  //   { key: "Lao People's Democratic Republic (the)", value: 'LA' },
  //   { key: 'Latvia', value: 'LV' },
  //   { key: 'Lebanon', value: 'LB' },
  //   { key: 'Lesotho', value: 'LS' },
  //   { key: 'Liberia', value: 'LR' },
  //   { key: 'Libya', value: 'LY' },
  //   { key: 'Liechtenstein', value: 'LI' },
  //   { key: 'Lithuania', value: 'LT' },
  //   { key: 'Luxembourg', value: 'LU' },
  //   { key: 'Macao', value: 'MO' },
  //   { key: 'Madagascar', value: 'MG' },
  //   { key: 'Malawi', value: 'MW' },
  //   { key: 'Malaysia', value: 'MY' },
  //   { key: 'Maldives', value: 'MV' },
  //   { key: 'Mali', value: 'ML' },
  //   { key: 'Malta', value: 'MT' },
  //   { key: 'Marshall Islands (the)', value: 'MH' },
  //   { key: 'Martinique', value: 'MQ' },
  //   { key: 'Mauritania', value: 'MR' },
  //   { key: 'Mauritius', value: 'MU' },
  //   { key: 'Mayotte', value: 'YT' },
  //   { key: 'Mexico', value: 'MX' },
  //   { key: 'Micronesia (Federated States of)', value: 'FM' },
  //   { key: 'Moldova (the Republic of)', value: 'MD' },
  //   { key: 'Monaco', value: 'MC' },
  //   { key: 'Mongolia', value: 'MN' },
  //   { key: 'Montenegro', value: 'ME' },
  //   { key: 'Montserrat', value: 'MS' },
  //   { key: 'Morocco', value: 'MA' },
  //   { key: 'Mozambique', value: 'MZ' },
  //   { key: 'Myanmar', value: 'MM' },
  //   { key: 'Namibia', value: 'NA' },
  //   { key: 'Nauru', value: 'NR' },
  //   { key: 'Nepal', value: 'NP' },
  //   { key: 'Netherlands (the)', value: 'NL' },
  //   { key: 'New Caledonia', value: 'NC' },
  //   { key: 'New Zealand', value: 'NZ' },
  //   { key: 'Nicaragua', value: 'NI' },
  //   { key: 'Niger (the)', value: 'NE' },
  //   { key: 'Nigeria', value: 'NG' },
  //   { key: 'Niue', value: 'NU' },
  //   { key: 'Norfolk Island', value: 'NF' },
  //   { key: 'Northern Mariana Islands (the)', value: 'MP' },
  //   { key: 'Norway', value: 'NO' },
  //   { key: 'Oman', value: 'OM' },
  //   { key: 'Pakistan', value: 'PK' },
  //   { key: 'Palau', value: 'PW' },
  //   { key: 'Palestine, State of', value: 'PS' },
  //   { key: 'Panama', value: 'PA' },
  //   { key: 'Papua New Guinea', value: 'PG' },
  //   { key: 'Paraguay', value: 'PY' },
  //   { key: 'Peru', value: 'PE' },
  //   { key: 'Philippines (the)', value: 'PH' },
  //   { key: 'Pitcairn', value: 'PN' },
  //   { key: 'Poland', value: 'PL' },
  //   { key: 'Portugal', value: 'PT' },
  //   { key: 'Puerto Rico', value: 'PR' },
  //   { key: 'Qatar', value: 'QA' },
  //   { key: 'Republic of North Macedonia', value: 'MK' },
  //   { key: 'Romania', value: 'RO' },
  //   { key: 'Russian Federation (the)', value: 'RU' },
  //   { key: 'Rwanda', value: 'RW' },
  //   { key: 'Réunion', value: 'RE' },
  //   { key: 'Saint Barthélemy', value: 'BL' },
  //   { key: 'Saint Helena, Ascension and Tristan da Cunha', value: 'SH' },
  //   { key: 'Saint Kitts and Nevis', value: 'KN' },
  //   { key: 'Saint Lucia', value: 'LC' },
  //   { key: 'Saint Martin (French part)', value: 'MF' },
  //   { key: 'Saint Pierre and Miquelon', value: 'PM' },
  //   { key: 'Saint Vincent and the Grenadines', value: 'VC' },
  //   { key: 'Samoa', value: 'WS' },
  //   { key: 'San Marino', value: 'SM' },
  //   { key: 'Sao Tome and Principe', value: 'ST' },
  //   { key: 'Saudi Arabia', value: 'SA' },
  //   { key: 'Senegal', value: 'SN' },
  //   { key: 'Serbia', value: 'RS' },
  //   { key: 'Seychelles', value: 'SC' },
  //   { key: 'Sierra Leone', value: 'SL' },
  //   { key: 'Singapore', value: 'SG' },
  //   { key: 'Sint Maarten (Dutch part)', value: 'SX' },
  //   { key: 'Slovakia', value: 'SK' },
  //   { key: 'Slovenia', value: 'SI' },
  //   { key: 'Solomon Islands', value: 'SB' },
  //   { key: 'Somalia', value: 'SO' },
  //   { key: 'South Africa', value: 'ZA' },
  //   { key: 'South Georgia and the South Sandwich Islands', value: 'GS' },
  //   { key: 'South Sudan', value: 'SS' },
  //   { key: 'Spain', value: 'ES' },
  //   { key: 'Sri Lanka', value: 'LK' },
  //   { key: 'Sudan (the)', value: 'SD' },
  //   { key: 'Surikey', value: 'SR' },
  //   { key: 'Svalbard and Jan Mayen', value: 'SJ' },
  //   { key: 'Sweden', value: 'SE' },
  //   { key: 'Switzerland', value: 'CH' },
  //   { key: 'Syrian Arab Republic', value: 'SY' },
  //   { key: 'Taiwan (Province of China)', value: 'TW' },
  //   { key: 'Tajikistan', value: 'TJ' },
  //   { key: 'Tanzania, United Republic of', value: 'TZ' },
  //   { key: 'Thailand', value: 'TH' },
  //   { key: 'Timor-Leste', value: 'TL' },
  //   { key: 'Togo', value: 'TG' },
  //   { key: 'Tokelau', value: 'TK' },
  //   { key: 'Tonga', value: 'TO' },
  //   { key: 'Trinidad and Tobago', value: 'TT' },
  //   { key: 'Tunisia', value: 'TN' },
  //   { key: 'Turkey', value: 'TR' },
  //   { key: 'Turkmenistan', value: 'TM' },
  //   { key: 'Turks and Caicos Islands (the)', value: 'TC' },
  //   { key: 'Tuvalu', value: 'TV' },
  //   { key: 'Uganda', value: 'UG' },
  //   { key: 'Ukraine', value: 'UA' },
  //   { key: 'United Arab Emirates (the)', value: 'AE' },
  //   {
  //     key: 'United Kingdom of Great Britain and Northern Ireland (the)',
  //     value: 'GB',
  //   },
  //   { key: 'United States Minor Outlying Islands (the)', value: 'UM' },
  //{ key: 'United States of America (the)', value: 'US' },
  //   { key: 'Uruguay', value: 'UY' },
  //   { key: 'Uzbekistan', value: 'UZ' },
  //   { key: 'Vanuatu', value: 'VU' },
  //   { key: 'Venezuela (Bolivarian Republic of)', value: 'VE' },
  //   { key: 'Viet Nam', value: 'VN' },
  //   { key: 'Virgin Islands (British)', value: 'VG' },
  //   { key: 'Virgin Islands (U.S.)', value: 'VI' },
  //   { key: 'Wallis and Futuna', value: 'WF' },
  //   { key: 'Western Sahara', value: 'EH' },
  //   { key: 'Yemen', value: 'YE' },
  //   { key: 'Zambia', value: 'ZM' },
  //   { key: 'Zimbabwe', value: 'ZW' },
];
